### PR TITLE
OAuth2 client_credentials incorrect response if credentials are incorrect

### LINKED ISSUE #685: OAuth2 client_credentials incorrect response if credentials are incorrect
The proper response should be a 401 with the following payload:

```json
{
  "error": "invalid_client"
}
```

But at least in the servlet example the response is the 500 error page (haven't verify the issue in the spring integrations)

```
curl -X POST -s -u "INVALID:INVALID" -d "grant_type=client_credentials" http://localhost:8080/oauth/token
```

Response

```html
<html><head><title>Apache Tomcat/7.0.68 - Error report</title><style><!--H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} P {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;}A {color : black;}A.name {color : black;}HR {color : #525D76;}--></style> </head><body><h1>HTTP Status 500 - Unable to invoke Stormpath controller: null</h1><HR size="1" noshade="noshade"><p><b>type</b> Exception report</p><p><b>message</b> <u>Unable to invoke Stormpath controller: null</u></p><p><b>description</b> <u>The server encountered an internal error that prevented it from fulfilling this request.</u></p><p><b>exception</b> <pre>java.lang.RuntimeException: Unable to invoke Stormpath controller: null
	com.stormpath.sdk.servlet.filter.mvc.ControllerFilter.filter(ControllerFilter.java:95)
	com.stormpath.sdk.servlet.filter.HttpFilter.doFilter(HttpFilter.java:249)
	com.stormpath.sdk.servlet.filter.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:65)
	com.stormpath.sdk.servlet.filter.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:60)
	com.stormpath.sdk.servlet.filter.account.AccountResolverFilter.filter(AccountResolverFilter.java:126)
	com.stormpath.sdk.servlet.filter.HttpFilter.doFilter(HttpFilter.java:249)
	com.stormpath.sdk.servlet.filter.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:65)
	com.stormpath.sdk.servlet.filter.StormpathFilter.filter(StormpathFilter.java:124)
	com.stormpath.sdk.servlet.filter.HttpFilter.doFilter(HttpFilter.java:249)
</pre></p><p><b>root cause</b> <pre>java.lang.NullPointerException
	com.stormpath.sdk.servlet.mvc.AccessTokenController.clientCredentialsAuthenticationRequest(AccessTokenController.java:245)
	com.stormpath.sdk.servlet.mvc.AccessTokenController.doPost(AccessTokenController.java:323)
	com.stormpath.sdk.servlet.mvc.AccessTokenController.handleRequest(AccessTokenController.java:174)
	com.stormpath.sdk.servlet.filter.mvc.ControllerFilter.filter(ControllerFilter.java:93)
	com.stormpath.sdk.servlet.filter.HttpFilter.doFilter(HttpFilter.java:249)
	com.stormpath.sdk.servlet.filter.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:65)
	com.stormpath.sdk.servlet.filter.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:60)
	com.stormpath.sdk.servlet.filter.account.AccountResolverFilter.filter(AccountResolverFilter.java:126)
	com.stormpath.sdk.servlet.filter.HttpFilter.doFilter(HttpFilter.java:249)
	com.stormpath.sdk.servlet.filter.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:65)
	com.stormpath.sdk.servlet.filter.StormpathFilter.filter(StormpathFilter.java:124)
	com.stormpath.sdk.servlet.filter.HttpFilter.doFilter(HttpFilter.java:249)
</pre></p><p><b>note</b> <u>The full stack trace of the root cause is available in the Apache Tomcat/7.0.68 logs.</u></p><HR size="1" noshade="noshade"><h3>Apache Tomcat/7.0.68</h3></body></html>
```

### PR DESCRIPTION
**Pull request by jarias**
Fixes #685

### CODE REVIEW

File: extensions/servlet/src/main/java/com/stormpath/sdk/servlet/config/DefaultFilterChainResolverFactory.java [hunk 1]
```diff
@@ -300,7 +300,7 @@ protected FilterChainResolver createInstance() throws ServletException {
             fcManager.createChain(sendVerificationUrlPattern, DefaultFilter.sendVerificationEmail.name());
         }
         if (!accessTokenChainSpecified) {
-            fcManager.createChain(accessTokenUrlPattern, DefaultFilter.accessToken.name());
+            fcManager.createChain(accessTokenUrlPattern, "anon," + DefaultFilter.accessToken.name());
```
Comment (dogeared) [inline extensions/servlet/src/main/java/com/stormpath/sdk/servlet/config/DefaultFilterChainResolverFactory.java]: why anon? This will end up being: `anon,access_token`?

Comment (jarias) [inline extensions/servlet/src/main/java/com/stormpath/sdk/servlet/config/DefaultFilterChainResolverFactory.java]: I think this is not needed, I was looking into how to avoid authentication for this endpoint, but realize the issue was the account resolver filter

Comment (dogeared) [inline extensions/servlet/src/main/java/com/stormpath/sdk/servlet/config/DefaultFilterChainResolverFactory.java]: Ok. Will you update and when CI passes, please merge! 👍

**Comment by dogeared** [comment]
LGTM - please merge 👍
