### PR TITLE
Ensure Stormpath RequestEventListener is called during failed authentications when using Spring Security

### LINKED ISSUE #367: Stormpath RequestEventListener does not work when SpringSecurity is enabled
For example, when SS LogoutHandlers are present in the Spring ApplicationContext, our StormpathHttpServletRequest.logout() method is not invoked - which in turn does not invoke our request event publisher.  Need to find another way of ensuring these events are triggered when SS is enabled.

### PR DESCRIPTION
**Pull request by lhazlewood**
Resolves #367

### CODE REVIEW

File: extensions/spring/stormpath-spring-security-webmvc/src/main/java/com/stormpath/spring/config/StormpathAuthenticationFailureHandler.java [hunk 1]
```diff
@@ -0,0 +1,89 @@
...
+import javax.servlet.ServletException;
+import javax.servlet.http.HttpServletRequest;
+import javax.servlet.http.HttpServletResponse;
+import java.io.IOException;
+
+/**
+ * A simple {@link AuthenticationFailureHandler} implementation that delegates to an actual/delegate handler for
+ * handling logic, but will then send a Stormpath {@link FailedAuthenticationRequestEvent} after delegate invocation.
+ * <p>This enables Stormpath web events to be sent in a Spring Security environment when
+ * encountering a Spring Security {@link AuthenticationException AuthenticationException}.</p>
```
Comment (mraible) [inline extensions/spring/stormpath-spring-security-webmvc/src/main/java/com/stormpath/spring/config/StormpathAuthenticationFailureHandler.java]: I believe you can remove the second `AuthenticationException` in this sentence.

File: extensions/spring/stormpath-spring-security-webmvc/src/test/groovy/com/stormpath/spring/config/CustomRequestEventListenerIT.groovy [hunk 2]
```diff
@@ -0,0 +1,68 @@
...
+import org.springframework.test.web.servlet.MockMvc
+import org.springframework.test.web.servlet.setup.MockMvcBuilders
+import org.springframework.web.context.WebApplicationContext
+import org.testng.annotations.BeforeMethod
+import org.testng.annotations.Test
+
+import static org.springframework.security.test.web.servlet.request.SecurityMockMvcRequestBuilders.formLogin
+import static org.springframework.security.test.web.servlet.response.SecurityMockMvcResultMatchers.unauthenticated
+import static org.springframework.security.test.web.servlet.setup.SecurityMockMvcConfigurers.*
+import static org.testng.Assert.*;
```
Comment (mraible) [inline extensions/spring/stormpath-spring-security-webmvc/src/test/groovy/com/stormpath/spring/config/CustomRequestEventListenerIT.groovy]: Do we allow `*` imports in tests? I've noticed that we don't allow them in sdk code.

**Comment by mraible** [comment]
I checked out this branch and ran `examples/spring-security-webmvc` locally. I was able to debug and confirm that `StormpathLogoutHandler#logout` is called when you hit http://localhost:8080/logout. Therefore, :+1:

File: extensions/spring/stormpath-spring-security-webmvc/src/main/java/com/stormpath/spring/config/StormpathAuthenticationFailureHandler.java (hunk 1 above)
Comment (lhazlewood) [inline extensions/spring/stormpath-spring-security-webmvc/src/main/java/com/stormpath/spring/config/StormpathAuthenticationFailureHandler.java]: Not really.  While the link will be generated correctly, the text shown will be the interface fully qualified name in the generated JavaDoc, not just `AuthenticationException`.  JavaDoc links have the first string be the link to the source code location, the 2nd string is the text you want to display.

**Comment by mrioan** [comment]
@lhazlewood code looks good to me. I tested Spring and Spring Boot and in both cases the failed authentication attempt triggered an event. You can considered this approved. Back to you

File: extensions/spring/stormpath-spring-security-webmvc/src/test/groovy/com/stormpath/spring/config/CustomRequestEventListenerIT.groovy (hunk 2 above)
Comment (lhazlewood) [inline extensions/spring/stormpath-spring-security-webmvc/src/test/groovy/com/stormpath/spring/config/CustomRequestEventListenerIT.groovy]: I think we should since this code isn't run in an application.  I personally hate having to import all my assert methods and easymock methods every. single. time. I need them.  My .02.

File: extensions/spring/stormpath-spring-security-webmvc/src/main/java/com/stormpath/spring/config/StormpathAuthenticationFailureHandler.java (hunk 1 above)
Comment (lhazlewood) [inline extensions/spring/stormpath-spring-security-webmvc/src/main/java/com/stormpath/spring/config/StormpathAuthenticationFailureHandler.java]: Ah, I think in this case it will not expand to the fully qualified name because the class is already imported into the current class?
