### PR TITLE
1295 - Added support for MCF password via Directory creation

### LINKED ISSUE #1295: Account with MCF password is not properly created via Directory
An account with MCF password created via `Application` works fine, while it fails for `Directory`.

You can use this test to validate that:

```
Application application = client.getResource(applicationUrl, Application.class);
Directory directory = client.getResource(dirUrl, Directory.class);

Account account = client.instantiate(Account.class);
String username = "deleteme" + UUID.randomUUID();
account.setEmail(username + "@mailinator.com")
                .setUsername(username)
                .setGivenName(username)
                .setSurname(username)
               .setPassword("$2a$12$ctIUO.W0pzIRTKHqK5Fl4uDWBB0ysSE3XJi9jcNAtRvdhUVAHnp2e"); //the password is Mario123 (created with https://www.dailycred.com/article/bcrypt-calculator)

// creation via application works fine, uncomment the following line and comment the directory one
// account = application.createAccount(Accounts.newCreateRequestFor(account).setPasswordFormat(PasswordFormat.MCF).build());

//creation via directory does not work properly
account = directory.createAccount(Accounts.newCreateRequestFor(account).setPasswordFormat(PasswordFormat.MCF).build());

AuthenticationResult authenticationResult = application.authenticateAccount(
                UsernamePasswordRequests.builder()
                        .setUsernameOrEmail(username)
                        .setPassword("Mario123")
                        .withResponseOptions(UsernamePasswordRequests.options().withAccount())
                        .build());

Assert.assertEquals(authenticationResult.getAccount().getUsername(), username);
```

See support ticket 11330

### PR DESCRIPTION
**Pull request by mrioan**
Resolves #1295

### CODE REVIEW

File: impl/src/main/java/com/stormpath/sdk/impl/directory/DefaultDirectory.java [hunk 1]
```diff
@@ -151,10 +151,16 @@ public Account createAccount(CreateAccountRequest request) {
         final Account account = request.getAccount();
         String href = getAccounts().getHref();
 
+        char querySeparator = '?';
+
         if (request.isRegistrationWorkflowOptionSpecified()) {
             href += "?registrationWorkflowEnabled=" + request.isRegistrationWorkflowEnabled();
```
Comment (dogeared) [inline impl/src/main/java/com/stormpath/sdk/impl/directory/DefaultDirectory.java]: can use `querySeparator` here

Comment (mrioan) [inline impl/src/main/java/com/stormpath/sdk/impl/directory/DefaultDirectory.java]: true!

**Comment by mrioan** [comment]
@dogeared I have improved the PR as suggested. Is this PR approved?
