### PR TITLE
Groups empty customData tests together and temporarily disables them.

### LINKED ISSUE #288: Temporarily disabled empty customData tests until backend hotfix is released
Right now, creating customData on a group fails. This behavior will be resolved on the backend, but is currently causing travis failures.

This will be reversed when the hotfix is pushed live.

The issue to reverse is here: https://github.com/stormpath/stormpath-sdk-java/issues/289

### PR DESCRIPTION
**Pull request by dogeared**
resolves #288

### CODE REVIEW

File: extensions/httpclient/src/test/groovy/com/stormpath/sdk/client/ApplicationCustomDataIT.groovy [hunk 1]
```diff
@@ -33,6 +33,48 @@ class ApplicationCustomDataIT extends AbstractCustomDataIT {
 
     Application application
 
+    // This is temporary and will be reversed when AM-2869 is released
```
Comment (mrioan) [inline extensions/httpclient/src/test/groovy/com/stormpath/sdk/client/ApplicationCustomDataIT.groovy]: This test is temporarily disabled since a backend issue is causing this test to fail. As soon as AM-2869 this test must be enabled.

**Comment by mrioan** [comment]
@dogeared This PR can be considered approved once my single comment is applied. Thanks!

**Comment by mrioan** [comment]
@dogeared back to you
