### PR TITLE
Issue 565

### LINKED ISSUE #565: Add Stormpath-Request-Id http header information to ResourceException
The "Stormpath-Request-Id" http header will make easier to track client exceptions to server-side requests, this will facilitate troubleshooting issues at times.

### PR DESCRIPTION
**Pull request by josebarrueta**
Resolves #565 

Current ResourceException message is:

```HTTP 404, Stormpath 404 (mailto:support@stormpath.com): The requested resource does not exist.```

After this PR is added to the SDK, the Stormpath-Request-Id information will be added to the message, to look like this:

```HTTP 404, RequestId: 8b687570-fb5c-11e5-9b05-d2ed6aa51ae6, Stormpath 404 (mailto:support@stormpath.com): The requested resource does not exist.```

### CODE REVIEW

**Comment by josebarrueta** [comment]
For some context in the PR:

Current ResourceException message is:

```HTTP 404, Stormpath 404 (mailto:support@stormpath.com): The requested resource does not exist.```

After this PR is added to the SDK, the Stormpath-Request-Id information will be added to the message, to look like this:

```HTTP 404, Stormpath-Request-Id 8b687570-fb5c-11e5-9b05-d2ed6aa51ae6, Stormpath 404 (mailto:support@stormpath.com): The requested resource does not exist.```

**Comment by dogeared** [comment]
Hey @josebarrueta:

Please fix the failing tests and add some specific tests with and without headers. After that, LGTM.

File: impl/src/main/java/com/stormpath/sdk/impl/http/HttpHeaders.java [hunk 1]
```diff
@@ -482,6 +484,26 @@ public String getPragma() {
...
+        return getFirst(STORMPATH_REQUEST_ID);
+    }
+
+    /**
+     * Sets the (new) value of the {@code Stormpath-Request-Id} header.
+     *
+     * @param stormpathRequestId - The value of the header.
+     * @since 1.0.RC9
+     */
+    public void setStormpathRequestId(String stormpathRequestId) {
```
Comment (lhazlewood) [inline impl/src/main/java/com/stormpath/sdk/impl/http/HttpHeaders.java]: Is a setter required?  Seems suspect to me since this is only set by the server.  Thoughts?

**Comment by lhazlewood** [comment]
Just a note for the rest of the Java SDK team - we're waiting on a few changes from @josebarrueta in this PR before we review again.

**Comment by josebarrueta** [comment]
Done with my updates.

File: impl/src/main/java/com/stormpath/sdk/impl/error/DefaultError.java [hunk 2]
```diff
@@ -71,4 +72,10 @@ public String getDeveloperMessage() {
     public String getMoreInfo() {
         return getString(MORE_INFO);
     }
+
+    @Override
+    public String getRequestId() {
+       return getString(REQUEST_ID);
```
Comment (mraible) [inline impl/src/main/java/com/stormpath/sdk/impl/error/DefaultError.java]: Indentation looks like it's off by a space.

Comment (josebarrueta) [inline impl/src/main/java/com/stormpath/sdk/impl/error/DefaultError.java]: How can you see that?

Comment (lhazlewood) [inline impl/src/main/java/com/stormpath/sdk/impl/error/DefaultError.java]: Look at the `r` line 78.  It is under the `l` in line 77.  This is 3 characters in.  Java indentation is 4 characters.

Look at line 73 by comparison.  The `r` is under the `i`, which is properly indented 4 characters.

Comment (josebarrueta) [inline impl/src/main/java/com/stormpath/sdk/impl/error/DefaultError.java]: is that important enough?

Comment (lhazlewood) [inline impl/src/main/java/com/stormpath/sdk/impl/error/DefaultError.java]: This one issue isn't that important, but Matt was flagging that you're not adhering to the code formatting standard of the project, so perhaps there might be more issues.

Formatting matters so whitespace 'noise' between commits (which does cause cognitive overhead) doesn't happen, and that probably is important.

Comment (lhazlewood) [inline impl/src/main/java/com/stormpath/sdk/impl/error/DefaultError.java]: Actually, I misread the line - it is currently indented 4 characters, so it looks good to me.

File: impl/src/main/java/com/stormpath/sdk/impl/error/DefaultError.java [hunk 3]
```diff
@@ -71,4 +72,10 @@ public String getDeveloperMessage() {
     public String getMoreInfo() {
         return getString(MORE_INFO);
```
Comment (lhazlewood) [inline impl/src/main/java/com/stormpath/sdk/impl/error/DefaultError.java]: This is the line that is actually not formatted correctly, but this code wasn't changed, so no need to deal with it in the PR review

File: api/src/main/java/com/stormpath/sdk/resource/ResourceException.java [hunk 4]
```diff
@@ -40,8 +41,15 @@
     private static String buildExceptionMessage(Error error) {
         Assert.notNull(error, "Error argument cannot be null.");
         StringBuilder sb = new StringBuilder();
-        sb.append("HTTP ").append(error.getStatus())
-                .append(", Stormpath ").append(error.getCode())
+        sb.append("HTTP ").append(error.getStatus());
+
+        String requestId = error.getRequestId();
+
+        if (Strings.hasText(requestId)) {
```
Comment (lhazlewood) [inline api/src/main/java/com/stormpath/sdk/resource/ResourceException.java]: Let's have this after the Stormpath status code in the string message (rather than separate the http status from the Stormpath status)

Comment (josebarrueta) [inline api/src/main/java/com/stormpath/sdk/resource/ResourceException.java]: k, updated format:

```HTTP 400, Stormpath 5114 (http://docs.stormpath.com/errors/5114), RequestId UUUU-IIII-DDDD: The specified application account store reference is invalid.```

**Comment by josebarrueta** [comment]
@lhazlewood the PR has been updated with latest comments.
