### PR TITLE
Resolves confirmPassword being stored as customData bug

### LINKED ISSUE #1097: confirmPassword is incorrectly stored as customData

### PR DESCRIPTION
**Pull request by dogeared**
Fixes #1097

### CODE REVIEW

File: extensions/servlet/src/test/groovy/com/stormpath/sdk/servlet/mvc/RegisterControllerTest.groovy [hunk 1]
```diff
@@ -336,25 +336,31 @@ public class RegisterControllerTest {
...
-
+        // We need to be sure that every non-standard account property is properly considered to be custom data
+        // Since there is no way to identify them automatically they have been hardcoded in RegisterController#ACCOUNT_PROPERTIES
+        // This test checks that this list is accurate.
+        //
+        // If the simple properties ever change in the account and this test fails then be sure to update RegisterController#ACCOUNT_PROPERTIES
+        // in order to allow this test to pass.
+        //
+        // confirmPassword is a special case. It needs to exist in RegisterController to ensure it's not added to customData, but it is
+        // NOT part of the defaultAccount.PROPERTY_DESCRIPTORS
```
Comment (mrioan) [inline extensions/servlet/src/test/groovy/com/stormpath/sdk/servlet/mvc/RegisterControllerTest.groovy]: Please add "Fix for https://github.com/stormpath/stormpath-sdk-java/issues/1097"

File: extensions/servlet/src/main/java/com/stormpath/sdk/servlet/mvc/RegisterController.java [hunk 2]
```diff
@@ -54,7 +54,7 @@
 public class RegisterController extends FormController {
 
     private static final Logger log = LoggerFactory.getLogger(RegisterController.class);
-    public static final List<String> ACCOUNT_PROPERTIES = Collections.unmodifiableList(Arrays.asList("email", "username", "password", "givenName", "middleName", "surname"));
+    public static final List<String> ACCOUNT_PROPERTIES = Collections.unmodifiableList(Arrays.asList("email", "username", "password", "confirmPassword", "givenName", "middleName", "surname"));
```
Comment (mrioan) [inline extensions/servlet/src/main/java/com/stormpath/sdk/servlet/mvc/RegisterController.java]: @dogeared I think we need to add a security note in the documentation (`registration.rst`) after the "What do these field definition properties mean?" table to let people know that any custom field of type `password` will anyway be stored in plain text in the Accounts' CustomData.

In case you are not familiar with what I mean by "type":  `stormpath.web.login.form.fields.myCustomSecretField.type = password`

**Comment by mrioan** [comment]
@dogeared back to you. Thanks!

File: extensions/servlet/src/main/java/com/stormpath/sdk/servlet/mvc/RegisterController.java (hunk 2 above)
Comment (dogeared) [inline extensions/servlet/src/main/java/com/stormpath/sdk/servlet/mvc/RegisterController.java]: Sure. I will update.

**Comment by dogeared** [comment]
updated per your comments @mrioan. Back to you.

File: docs/source/registration.rst [hunk 3]
```diff
@@ -384,6 +384,9 @@ When the registration form is rendered, this field will be added:
 
 When the form is submitted, the field's name and value will be added automatically to the account's custom data.
 
+**NOTE:** If the ``type`` of a custom form field is ``password``, input on the field will be masked as usual. However,
```
Comment (mrioan) [inline docs/source/registration.rst]: @dogeared I built the docs but I could not find this change in Servlet and in Zuul. I see there are more `registration.rst` files that are not changed. Additionally I have second thoughts about the location. I think the proper place for this note is after the text `When the form is submitted, the field’s name and value will be added automatically to the account’s custom data.` (after the registration form is shown. Additionally I would not use "note" I think ".. caution:: Clear Text for Passwords" is better. See: `request-authentication.rst` and search for `HTTP Basic authentication sends the *raw* credentials over the network.  Basic Authentication should only be used over HTTPS connections and never over standard HTTP.` to see how that Caution box is created

File: extensions/servlet/src/test/groovy/com/stormpath/sdk/servlet/mvc/RegisterControllerTest.groovy (hunk 1 above)
Comment (mrioan) [inline extensions/servlet/src/test/groovy/com/stormpath/sdk/servlet/mvc/RegisterControllerTest.groovy]: @dogeared this comment was not addressed. Thanks

**Comment by mrioan** [comment]
@dogeared For some reason this comment is not showing up, please see: https://github.com/stormpath/stormpath-sdk-java/pull/1098#discussion_r87026241. Thanks!

File: docs/source/registration.rst (hunk 3 above)
Comment (dogeared) [inline docs/source/registration.rst]: Agreed about using `caution`. The placement of the caution is exactly where you are suggesting. Am I missing something? I will look into the docs build issue. The only other locations I see `registration.rst` files are in `build` folders.

**Comment by dogeared** [comment]
@mrioan - updated. Back to you.

**Comment by mrioan** [comment]
@dogeared Approved! Feel free to merge.
