### PR TITLE
Login with Social Provider does not trigger RequestEventListener

### LINKED ISSUE #737: Login with Social Provider does not trigger RequestEventListener
After a successful/failed Google/Facebook/etc login (with and without IDSite) we should get notified at a registered `RequestEventListener`. Currently that is not happening.

### PR DESCRIPTION
**Pull request by jarias**
Fixes #737

### CODE REVIEW

File: extensions/servlet/src/main/java/com/stormpath/sdk/servlet/config/impl/DefaultConfig.java [hunk 1]
```diff
@@ -32,13 +34,7 @@
...
 import javax.servlet.ServletContext;
 import javax.servlet.ServletException;
-import java.util.ArrayList;
-import java.util.Collection;
-import java.util.Collections;
-import java.util.LinkedHashMap;
-import java.util.List;
-import java.util.Map;
-import java.util.Set;
+import java.util.*;
```
Comment (mraible) [inline extensions/servlet/src/main/java/com/stormpath/sdk/servlet/config/impl/DefaultConfig.java]: Change to have expanded imports like it was before.

File: extensions/spring/stormpath-spring-webmvc/src/main/java/com/stormpath/spring/config/AbstractStormpathWebMvcConfiguration.java [hunk 2]
```diff
@@ -40,76 +40,21 @@
...
-import com.stormpath.sdk.servlet.filter.oauth.DefaultAccessTokenRequestAuthorizer;
-import com.stormpath.sdk.servlet.filter.oauth.DefaultAccessTokenResultFactory;
-import com.stormpath.sdk.servlet.filter.oauth.DefaultRefreshTokenAuthenticationRequestFactory;
-import com.stormpath.sdk.servlet.filter.oauth.DefaultRefreshTokenResultFactory;
-import com.stormpath.sdk.servlet.filter.oauth.OriginAccessTokenRequestAuthorizer;
-import com.stormpath.sdk.servlet.filter.oauth.RefreshTokenAuthenticationRequestFactory;
-import com.stormpath.sdk.servlet.filter.oauth.RefreshTokenResultFactory;
+import com.stormpath.sdk.servlet.filter.*;
+import com.stormpath.sdk.servlet.filter.account.*;
+import com.stormpath.sdk.servlet.filter.oauth.*;
```
Comment (mraible) [inline extensions/spring/stormpath-spring-webmvc/src/main/java/com/stormpath/spring/config/AbstractStormpathWebMvcConfiguration.java]: Change to have individual imports.

**Comment by mraible** [comment]
LTGM once wildcard imports are fixed.
