### PR TITLE
1025 fixing NPE in cookie account resolver

### LINKED ISSUE #1025: NullPointerException when trying to delete token in CookieAccountResolver
There is a bug in this line: https://github.com/stormpath/stormpath-sdk-java/blob/master/extensions/servlet/src/main/java/com/stormpath/sdk/servlet/filter/account/CookieAccountResolver.java#L146

When the `access_token` or `refresh_token` are not present the `delete` operation causes a `NullPointerException`.

`Delete` operation must check cookie is not null.

See https://stormpath.zendesk.com/agent/tickets/9582

### PR DESCRIPTION
**Pull request by mzumbadoate**
fixes #1025

### CODE REVIEW

**Comment by jarias** [comment]
LGTM but we need to fix the build issue we discuss yesterday in Slack.

File: extensions/servlet/src/main/java/com/stormpath/sdk/servlet/filter/account/CookieAccountResolver.java [hunk 1]
```diff
@@ -106,7 +106,7 @@ protected Account getAccount(HttpServletRequest request, HttpServletResponse res
     }
 
     protected void deleteCookie(HttpServletResponse response, Cookie cookie) {
-        if (!response.isCommitted()) {
+        if (!response.isCommitted() && cookie != null) {
```
Comment (dogeared) [inline extensions/servlet/src/main/java/com/stormpath/sdk/servlet/filter/account/CookieAccountResolver.java]: @mzumbadoate - please just add a comment referencing the issue this change resolves. Then, it's ready to merge!
