### PR TITLE
1212 Fix typo in header name.

### LINKED ISSUE #1212: Stormpath-Client-Request-Id header has a typo
current header is: `X-Stormapth-Client-Request-Id` instead of `X-Stormpath-Client-Request-Id`.

### PR DESCRIPTION
**Pull request by josebarrueta**
Fixes #1212

### CODE REVIEW

File: extensions/httpclient/src/test/groovy/com/stormpath/sdk/client/ClientIT.groovy [hunk 1]
```diff
@@ -167,28 +166,22 @@ abstract class ClientIT {
...
             assertEquals(re.status, 404)
             assertEquals(re.getCode(), 404)
         }
-
-        assertTrue(e instanceof ResourceException)
     }
 
-    protected void updatedSaveableError(Saveable input, int expectedErrorCode){
-        Throwable e = null;
+    static void updatedSaveableError(Saveable input, int expectedErrorCode) {
```
Comment (dogeared) [inline extensions/httpclient/src/test/groovy/com/stormpath/sdk/client/ClientIT.groovy]: why static?

**Comment by dogeared** [comment]
@josebarrueta - only one comment about `static` on method in test.

File: extensions/httpclient/src/test/groovy/com/stormpath/sdk/client/ClientIT.groovy (hunk 1 above)
Comment (josebarrueta) [inline extensions/httpclient/src/test/groovy/com/stormpath/sdk/client/ClientIT.groovy]: It was an Intellij recommendation, I think the reason was because there is no instance state require in the method.
