### PR TITLE
1241 - Fixing CORS issue for Angular

### LINKED ISSUE #1241: CORS support is broken in stormpath-default-spring-boot-starter in 1.3.0+
Steps to reproduce:

1. git clone https://github.com/stormpath/stormpath-angularjs-access-control-cors-example
2. cd into the `stormpath-angularjs-access-control-cors-example` directory and run `mvn spring-boot:run`.
3. In another terminal window, cd into the same directory and run `npm i && gulp`. This will open your default browser and you should be able to login to the app.
4. Cancel the Maven command and upgrade to 1.3.1 by changing `pom.xml` to use version `1.3.1` for the `stormpath-default-spring-boot-starter` dependency. You'll also need to modify `SecurityConfiguration.java` to remove `http.apply(stormpath()`. [This PR](https://github.com/stormpath/stormpath-angularjs-access-control-cors-example/pull/1/files) shows both of these upgrade steps.
5. Run `mvn spring-boot:run` and try to login with the client again (you may have to delete cookies). 
6. You will see an error but the expected outcome is a successful login.

screen shot 2017-01-17 at 2 54 17 pm

### PR DESCRIPTION
**Pull request by mrioan**
Resolves #1241

### CODE REVIEW

File: extensions/spring/boot/stormpath-spring-security-webmvc-spring-boot-starter/src/main/java/com/stormpath/spring/boot/autoconfigure/StormpathWebSecurityAutoConfiguration.java [hunk 1]
```diff
@@ -150,8 +150,8 @@ public AuthenticationEntryPoint stormpathAuthenticationEntryPoint() {
     /**
      * @since 1.3.0
      */
-    @Bean
-    @ConditionalOnMissingBean
+    @Bean //we cannot add @ConditionalOnMissingBean, it will avoid this bean to be created when the BOM is used to create an application. Fix for: https://github.com/stormpath/stormpath-sdk-java/issues/1241
```
Comment (dogeared) [inline extensions/spring/boot/stormpath-spring-security-webmvc-spring-boot-starter/src/main/java/com/stormpath/spring/boot/autoconfigure/StormpathWebSecurityAutoConfiguration.java]: /*
We cannot @ConditionalOnMissingBean. 
When using the spring boot starter parent, it has a CorsConfigurationSource that would prevent this bean from being used.
Refer to: https://github.com/stormpath/stormpath-sdk-java/issues/1241
*/

Comment (mrioan) [inline extensions/spring/boot/stormpath-spring-security-webmvc-spring-boot-starter/src/main/java/com/stormpath/spring/boot/autoconfigure/StormpathWebSecurityAutoConfiguration.java]: sure
